### ISSUE TITLE
vscode extension versioning considerations

### ISSUE THREAD

**Issue by djzager** [konveyor/editor-extensions#12]
How is our extension going to deal with min/max versions of VSCode, identifying incompatibilities, etc?

**Comment by rszwajko** [comment]
The minimum VS Code version required  by the extension is configured in the extension manifest (`package.json`) using `engine` property i.e.
```
"engines": {
    "vscode": "^1.93.0"
  }
```
According to [the docs](https://code.visualstudio.com/api/references/extension-manifest) `engine` is:
>An object containing at least the vscode key matching the versions of VS Code that the extension is [compatible](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#visual-studio-code-compatibility) with. Cannot be *. For example: ^0.10.5 indicates compatibility with a minimum VS Code version of 0.10.5.

**Comment by djzager** [comment]
I'm going to close this work as completed as my understanding is we have determine there is no work for us to do right now. As our extension ages it will become an issue.

Please reopen if I misunderstood.
