### ISSUE TITLE
Create "Apply fix" code action

### ISSUE THREAD

**Issue by rszwajko** [konveyor/editor-extensions#48]
1. action is triggered by the server once the suggested fix is computed
2. the fix is a git diff as text inside `message` prop
3. action opens a diff view that allows the user to accept or reject changes

**Comment by rszwajko** [comment]
Problems with using the [built-in multi diff editor](https://github.com/microsoft/vscode/blob/61b0fe7e0c74e892323ecf14490eb2160cef33ef/src/vs/workbench/contrib/multiDiffEditor/browser/multiDiffEditor.ts#L33) 
1. works only for registered schemes - current API does not expose API to register custom resolvers so we are limited to existing ones: . In practice this would require to masquerade as a SCM ( Source Control Management ) provider.
![Image](https://github.com/user-attachments/assets/6615c43a-f01d-4ee2-83cf-1be30ffbbe54)

2. requires modifying a virtual resource (left side is existing file, right side is suggested document, modifications are done on the righ side). However virtual documents are read only - at least according to Continue  which uses a workaround -  maintains suggestions as [hidden temporary files ](https://github.com/continuedev/continue/blob/056a68d06186b567510f379fd27990896b46f15c/extensions/vscode/src/diff/horizontal.ts#L34)

**Comment by sjd78** [comment]
Thinking about it as doing a code review is a good comparison.

**Comment by rszwajko** [comment]
Implemented in chain of PRs ending with https://github.com/konveyor/editor-extensions/pull/93
