### ISSUE TITLE
Should we release during weekends?

### ISSUE THREAD

**Issue by savitharaghunathan** [konveyor/editor-extensions#52]
I just noticed that the nightly releases over the weekend and if it doesnt have new code merged are all the same except new tags. May be we need to add a check?

**Comment by dymurray** [comment]
To add this, maybe just run `git diff` and if it returns with no output don't release?

**Comment by savitharaghunathan** [comment]
@dymurray : I need to sync with @djzager but we might only want to release when there is a new tag and not on nightly basis. I will update this task once I know more

**Comment by djzager** [comment]
I believe the correct solution is to simply have a workflow that runs when tags are created and creates the associated release with all of the vscode extension artifacts as assets. IIRC what we did in the operator repository, we should be able to run this on workflow_dispatch and it'll just create the tag for us at the head of whatever branch we run it from.

**Comment by savitharaghunathan** [comment]
ref: https://github.com/konveyor/editor-extensions/pull/63
