### ISSUE TITLE
Implementation of full happy path integrating IDE with Kai

### ISSUE THREAD

**Issue by dymurray** [konveyor/editor-extensions#57]
# History

At the end of Sprint 1, what we demonstrated was a VSCode extension that leveraged our analyzer-lsp JSONRPC server (here called kai-analyzer) to perform rules based analysis of an application in the active VSCode editor workspace. The resulting "RuleSets" were then processed and added to our extensions state as well as the RuleSet's incidents being added as vscode.Diagnostics (viewable in the editor's "Problems" panel). Lastly, we demonstrated a functional webview panel where problems could be viewed, sorted, filtered, and searched.

**Comment by sjd78** [comment]
Happy path is available.  I think this issue can be closed once we finish out the remaining open sub and sub-sub issues.
