### ISSUE TITLE
[vscode] Integrate kai/rpc-server

### ISSUE THREAD

**Issue by dymurray** [konveyor/editor-extensions#58]
This task is considered complete when the [kai/rpc-server](https://github.com/konveyor/kai/tree/6fd53e035e8e86593c81d640998aa76b5998d5d6/kai/rpc_server) is integrated into the VSCode editor extension.

This includes:
1. (In KAI) https://github.com/konveyor/kai/issues/433
2. #62 
3. #64
4. #65

**Comment by sjd78** [comment]
All sub-tasks are complete, therefore the task itself is complete!
