### ISSUE TITLE
Enhance IDE release workflow to include proper builds for windows/linux/mac

### ISSUE THREAD

**Issue by dymurray** [konveyor/editor-extensions#61]
Expanding on this a bit. There are a handful of things we need:

1. We need to pull the [rulesets](https://github.com/konveyor/rulesets), [java-analyzer-bundle](https://github.com/konveyor/java-analyzer-bundle), [kai-analyzer](https://github.com/konveyor/kai/tree/feature/repository-level-awareness/kai-analyzer), [kai/rpc-server](https://github.com/konveyor/kai/tree/6fd53e035e8e86593c81d640998aa76b5998d5d6/kai/rpc_server). Not just include them in our source tree directly. https://github.com/konveyor/kantra is doing stuff to bring these together for containerless analysis so we could beg/borrow/steal from that effort.
2. Be mindful of packaged extension size...if we can make sure windows stuff goes only into windows vsix packaged 👍 
3. This work probably obsoletes https://github.com/konveyor/editor-extensions/issues/52 because once we have this we should cut a legit release (even if it's just a tagged dev build).
4. Once we don't have binaries included in our source, we'll need a documented mechanism for folks to get these assets for development workflows. Maybe the script(s) that prep for packaging can be reused somehow?

**Comment by djzager** [comment]
Note mentioned by @sjd78 that we should include build info with our vscode extension + kai-analyzer + kai/rpc-server.

**Comment by sjd78** [comment]
This issue is mostly complete after the following PRs:
  - #120 
  - #121 
  - #122
  - #130 
  - #136 

The only remaining work is to add some docs to the base `README.md` on how to (1) download assets for dev work, and (2) build the vsix from sources.

**Comment by sjd78** [comment]
Spinning off the doc work to #150.
