### ISSUE TITLE
[vscode] mock analyzerClient.getSolution

### ISSUE THREAD

**Issue by djzager** [konveyor/editor-extensions#68]
Once we know the request/response we are going to send/receive to kai/rpc-server to `getCodeplanAgentSolution` in order to generate a solution for a particular violation, we should be able to mock or fake. This could be as simple as adding comments or removing lines, just something that would allow us to reliably exercise what the response would look like so we can develop the user experience for accept/rejecting fix.

**Comment by rszwajko** [comment]
Completed with #91
