### ISSUE TITLE
[vscode/editor] in editor view of specific proposed changes

### ISSUE THREAD

**Issue by djzager** [konveyor/editor-extensions#70]
When we are presenting the user with the response we got from the kai/rpc-server, one thing that would be really helpful is if the user could gain additional context on the proposed change by, clicking the filename for the codeblock or clicking the codeblock itself, opening that file in the editor where the proposed change is to be made. Additionally, we may elect to show the change in the editor with the option to accept/reject.

**Comment by djzager** [comment]
Now that we have removed #69 from the minimum demoable thing, the scope of this effort has increased along with https://github.com/konveyor/editor-extensions/issues/67 , specifically this comment https://github.com/konveyor/editor-extensions/issues/67#issuecomment-2443145629.

The important notes about how this effort has changed:
1. The webview will message the diff viewer with the proposed solution after kai/rpc-server has responded to our solution request and we have performed any necessary post processing.
1. The webview will be "disabled", preventing user input while the user works through the proposed solution.
1. The diff-viewer must notify the webview when the user has "finished" reconciling the proposed solution.

**Comment by rszwajko** [comment]
Most of the scope implemented in https://github.com/konveyor/editor-extensions/pull/79
The missing part is implementing the accept/reject buttons in the editor itself (i.e. code lense style). Right now it's implemented in the Konveyor Resolution view (native VS Code tree view).

**Comment by rszwajko** [comment]
Missing parts implemented in #102

**Comment by djzager** [comment]
I think this is done. Can we close this @rszwajko ?
