### ISSUE TITLE
repository needs github actions to perform checks on every PR

### ISSUE THREAD

**Issue by djzager** [konveyor/editor-extensions#9]
In order to prevent regressions that slow progress, we must introduce some basic PR Checks that run to make sure that we can:

* Build our extension
* Build any of our utilities (thinking the konveyor-analyzer bin)
* Run our extension
* Run any/all tests
* ???

**Comment by rszwajko** [comment]
Most points implemented in #15 
> Build our extension
>
Done
> Build any of our utilities (thinking the konveyor-analyzer bin)
>
TODO
>Run our extension
>
Done. We run the tests in a virtual display - as far as I understand this should work the same as local testing (which opens a VS Code instance). 
> Run any/all tests
>
Done via `vscode-test` - we might want to run ordinary unit tests in headless mode (if there would be too many of them)

**Comment by djzager** [comment]
Closing this one as done. We have done all we need to for right now. With the analyzer server stuff going into kai, there is not much for us to do right now.

Please reopen if I misunderstood our status.
